services:
  - type: web
    name: stany-min-tv1
    env: php
    plan: free
    buildCommand: echo "No build required for PHP"
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.2
